### ISSUE TITLE
Unable to open Role Documenter due to an error: Missing XrmToolBox.PluginsStore

### ISSUE THREAD

**Issue by ingerAH-PP** [santoshCRM/Export-Security-Role#18]
I have experienced a similar issue related to the tools "Bulk Data Updater" and "FetchXML Builder", ref. https://github.com/rappen/FetchXMLBuilder/issues/987
I noticed that there same issue occurs for other tools as well, ref https://github.com/MscrmTools/XrmToolBox/issues/1294, and now I am experiencing it with the Role Documenter, but there is a difference in the version of the missing file.

XrmToolBox: v.1.2023.12.68
Role Documenter: v.1.2021.6.12

![image](https://github.com/santoshCRM/Export-Security-Role/assets/51701932/84dfacac-a678-4e1a-847e-a93e74713de2)

**Comment by lambeaulady** [comment]
I see the same error message for Role Documenter 2/2/24. If it is no longer being supported/maintained can it be removed from the Tool Library?

**Comment by LinkeD365** [comment]
HI

I have updated this tool to the latest version of XrmTOolbox. Please try and let me know if it is now working.   
  
Unfortunately, this is volunteer project. If anyone wants to create a pull request they are more than welcome if I dont fix things quick enough

**Comment by ingerAH-PP** [comment]
Version 1.2024.2.4 (latest) works (with xrm toolbox version 1.2023.12.68) :)
