### ISSUE TITLE
Exporting won't export last row

### ISSUE THREAD

**Issue by maattaa** [santoshCRM/Export-Security-Role#2]
When exporting, the last row doesn't seem to get exported properly. Preview shows it, but the export is missing it. I'm using v1.2019.11.15 with XrmToolBox v1.2020.6.40. Tested in different online v9.1 environments, and happened in all roles tested.
![EXCEL_ty4MJq2iPx](https://user-images.githubusercontent.com/60356709/85509302-69d35680-b5fe-11ea-9528-99f7d91592ba.jpg)

**Comment by santoshCRM** [comment]
Thanks for Response I will correct it and publish.

**Comment by santoshCRM** [comment]
This issue is fixed. Download updated plugin from below link
https://github.com/santoshCRM/Export-Security-Role/blob/master/Savants.ExportSecurityRole%20v1.2019.11.15.zip
 
for more information check my blog
https://dotnetdeveloper2012.blogspot.com/2018/09/dynamics-crm-export-security-role.html
